### ISSUE TITLE
Add more twitter plugins

### ISSUE THREAD

**Issue by piyushchauhan** [piyushchauhan/iitp_pages#44]
There are no Twitter handle plugins currently.

 - [ ] Modify the `README.md` with the instructions to add Twitter Plugin.
 - [ ] Add twitter handles in new section. *You can use `row` or `section` class of bootstrap

**Comment by mehtankush** [comment]
@piyushchauhan I can take this up. 

To understand the issue, you want Tweets by nss_iitp embedded in a new section, right?

**Comment by mehtankush** [comment]
Raised #51
