### ISSUE TITLE
Use Bootstrap CDN

### ISSUE THREAD

**Issue by piyushchauhan** [piyushchauhan/iitp_pages#60]
Adding remove the current bootstrap files and then use the bootstrap CDN of the same version. Dont use latest bootstrap CDN.

**Comment by shuen-yasui** [comment]
Hello. May I help with this issue?

**Comment by piyushchauhan** [comment]
Yeah sure go ahead

**Comment by shuen-yasui** [comment]
Please review PR when you get a chance.

**Comment by piyushchauhan** [comment]
Merge and close
